use-abbreviated-prefix: false
save-arena-on-edit: false
timers:
    pregame-countdown: 60
    spawn-shield: 3
join-to-lobby: true
global-lobby:
    x: 100
    y: 66
    z: 100
    yaw: 0
    pitch: 0
    world: world