name: OneInTheGun
main: com.entrocorp.linearlogic.oneinthegun.OITG
version: 0.0.1
author: LinearLogic
permissions:
    oneinthegun.arena.signs:
        description: Permission to create and destroy arena signs
        default: op