name: OneInTheGun
main: com.entrocorp.linearlogic.oneinthegun.OITG
version: 0.0.1
author: LinearLogic
commands:
    oitg:
        description: Root command
        usage: /oitg [args]
permissions:
    oneinthegun.arena.create:
        description: Permission to create arenas
        default: op
    oneinthegun.arena.delete:
        description: Permission to delete arenas
        default: op
    oneinthegun.arena.info:
        description: Permission to view arena round info and settings
        default: true
    oneinthegun.arena.join:
        description: Permission to join arenas
        default: true
    oneinthegun.arena.kick:
        description: Permission to kick players from arenas
        default: op
    oneinthegun.arena.leaderboard:
        description: Permission to view arena leaderboards
        default: true
    oneinthegun.arena.list:
        description: Permission to list arenas
        default: true
    oneinthegun.arena.save:
        description: Permission to save an arena (used if the 'save-arena-on-edit' node is set to 'false' in the config)
        default: op
    oneinthegun.arena.setlobby:
        description: Permission to place the lobby of an arena
        default: op
    oneinthegun.arena.signs:
        description: Permission to create and destroy arena signs
        default: op
    oneinthegun.arena.spawns.add:
        description: Permission to add arena spawn points
        default: op
    oneinthegun.arena.spawns.clear:
        description: Permission to clear arena spawn points
        default: op
    oneinthegun.arena.toggleclosed:
        description: Permission to open and close arenas
        default: op
    oneinthegun.reload:
        description: Permission to reload the config
        default: op
    oneinthegun.setgloballobby:
        description: Permission to place the global lobby
        default: op